# Generated by Django 6.0.3 on 2026-03-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_group_alter_user_email_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role', models.Case(models.When(models.Q(('is_staff', True), ('is_superuser', True)), then=models.Value('ADMIN')), models.When(models.Q(('is_staff', True), ('is_superuser', False)), then=models.Value('MODERATOR')), default=models.Value('USER')))), name='role_check'),
        ),
    ]
