# Generated by Django 6.0.2 on 2026-02-25 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='breed name')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
            ],
            options={
                'verbose_name': 'breed',
                'verbose_name_plural': 'breeds',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='dog name')),
                ('photo', models.ImageField(null=True, upload_to='dogs/', verbose_name='photo')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed')),
            ],
            options={
                'verbose_name': 'dog',
                'verbose_name_plural': 'dogs',
                'ordering': ('name', 'breed'),
            },
        ),
    ]
