# Generated by Django 6.0.2 on 2026-02-27 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('name',), 'verbose_name': 'порода', 'verbose_name_plural': 'породы'},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ('name', 'breed'), 'verbose_name': 'собака', 'verbose_name_plural': 'собаки'},
        ),
        migrations.AddField(
            model_name='dog',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=64, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed', verbose_name='порода'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=64, verbose_name='кличка'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(null=True, upload_to='dogs/', verbose_name='фото'),
        ),
    ]
