# Generated by Django 6.0.2 on 2026-03-03 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_breed_options_alter_dog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('name',), 'verbose_name': 'breed', 'verbose_name_plural': 'breeds'},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ('name', 'breed'), 'verbose_name': 'dog', 'verbose_name_plural': 'dogs'},
        ),
        migrations.AddField(
            model_name='dog',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed', verbose_name='breed'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=64, verbose_name='dog name'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(null=True, upload_to='dogs/', verbose_name='photo'),
        ),
    ]
