# Generated by Django 6.0.3 on 2026-03-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_owner_pedigree'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
    ]
