# Generated by Django 6.0.3 on 2026-03-19 01:45

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_alter_comment_options_alter_comment_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'breed', 'verbose_name_plural': 'breeds'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': (models.OrderBy(django.db.models.functions.comparison.Coalesce('updated', 'created'), descending=True),), 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name': 'dog', 'verbose_name_plural': 'dogs'},
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='views'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='ancestor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='dogs.dog', verbose_name='ancestor'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='descendant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='dogs.dog', verbose_name='descendant'),
        ),
    ]
